slsfi/digital-edition-frontend-ng

- src/app/dialogs/popovers/view-options/view-options.popover.scss
Instead of setting a background-color on the toggle items target only the labels of the toggles.
> style(view-options): move style targets to toggle labels

- src/theme/ionic/_ion-input.scss
Fixes the reduced height of the ion-input element introduced in Ionic 7.6.0 for the facsimile page number inputs.
> style: fix ion-input element height for facsimile page nr inputs

- CHANGELOG.md
- src/app/services/html-parser.service.ts
- src/assets/config/config.ts
Previously doodle illustrations had to be in the frontend in the path src/assets/images/verk/, now they must be in the backend. Use collections.mediaCollectionMappings in config.ts to map the id of the collection with doodles to the id of the media collection that holds the images in the backend.
> refactor: get doodle illustrations from backend using media collection mapping

- CHANGELOG.md
- src/app/services/html-parser.service.ts
Illustration image path mapping to media collections is performed solely based on the presence of the CSS class name `est_figure_graphic` on `img` elements – not as previously based on the image `src` containing `assets/images/verk/` in it. Thus, illustration images that are to be mapped to media collections must have just the image file names in the `src` attributes, rather than `images/verk/<filename>` as previously. Images with absolute URLs in `src` are never mapped regardless of class names.
> refactor: change basis for illustration image mapping to media collections

- CHANGELOG.md
- src/app/components/collection-text-types/facsimiles/facsimiles.component.ts
- src/app/components/collection-text-types/variants/variants.component.ts
- src/app/dialogs/modals/download-texts/download-texts.modal.ts
- src/app/pages/collection/foreword/collection-foreword.page.ts
- src/app/pages/collection/introduction/collection-introduction.page.ts
- src/app/pages/collection/title/collection-title.page.ts
- src/app/services/comment.service.ts
- src/app/services/html-parser.service.ts
Fixing image paths in collection pages from `images/` to `assets/images/` is done specifically at the start of `src` attribute values – not for any occurrence of the string `images/`.
> refactor: limit image path fixing in collection components to src attributes

- CHANGELOG.md
- src/app/services/html-parser.service.ts
The regex sanitization is unnecessary because the query results are anyway parsed as HTML, only text nodes are retained and any `<`, `>` characters are converted to their corresponding HTML entities.
> fix: remove incomplete regex sanitization of script tags in search query results

- .github/workflows/docker-build-and-push.yml
This simplifies things by building and storing docker images directly in Github.
The images for this repository would be: ghcr.io/slsfi/digital-edition-frontend-ng
Tags for images would be the same as the tags for the releases in Github.
> Add github actions workflow definition

- CHANGELOG.md
- compose.yml
The Docker images for the base app are no longer built by and stored in DockerHub, but GitHub using actions.
> build: change base app Docker image in compose.yml

- CHANGELOG.md
- src/app/components/collection-text-types/facsimiles/facsimiles.component.ts
- src/app/components/collection-text-types/variants/variants.component.ts
- src/app/dialogs/modals/download-texts/download-texts.modal.ts
- src/app/pages/collection/foreword/collection-foreword.page.ts
- src/app/pages/collection/introduction/collection-introduction.page.ts
- src/app/pages/collection/title/collection-title.page.ts
- src/app/services/comment.service.ts
- src/app/services/html-parser.service.ts
- src/assets/config/config.ts
`config.collections.replaceImageAssetsPaths`.
The new config option defaults to `true`, which corresponds to the old behaviour. When this option is `true`, `src` attribute values starting with `images/` in the HTML of collection texts are replaced with `assets/images/`, which is the correct path to the image assets folder. Setting the new config option to `false` improves app performance.
> feature: add config option to replace image assets paths in collection texts

- CHANGELOG.md
- src/app/components/menus/top/top-menu.component.html
- src/app/components/menus/top/top-menu.component.ts
- src/assets/config/config.ts
Added config option to specify the dimensions of the site logo in the top menu: `config.component.topMenu.siteLogoDimensions`. The new config option is an object containing nested objects for specifying the height and width of the logo in both desktop and mobile mode. If the option is omitted, it defaults to an empty object, which corresponds to the old behaviour where the height and width attributes of the HTMLImageElement of the logo are not set. Setting the dimensions reduces layout shifts during page loading. Structure of the `siteLogoDimensions` with example values:
```
siteLogoDimensions: {
default: {
height: 56,
width: 173
},
mobile: {
height: 56,
width: 56
}
}
```
> feature: define site logo dimensions in config

- CHANGELOG.md
- package-lock.json
- package.json
In a fresh Angular 17 app @angular/compiler is in dependencies, not devDependencies.
> build(deps): move @angular/compiler to production dependencies

- CHANGELOG.md
- src/app/directives/math-jax.directive.ts
For projects that have MathJax enabled the MathJax script should run only in the browser, trying to run in on the server will throw an error.
> fix: run MathJax only in browser

- src/app/components/static-html/static-html.component.ts
In the browser the dynamic collection menu is loaded anyway, so no need to load the static one.
> perf: skip loading static collection menu in the browser

- CHANGELOG.md
- src/app/pages/collection/text/collection-text.page.html
Defer loading of the facsimile component on the collection text page to the browser. This increases server-side rendering performance since the component isn’t rendered on the server.
> perf: defer loading facsimiles to browser

- CHANGELOG.md
- src/app/pages/collection/text/collection-text.page.html
Defer loading of the illustrations component on the collection text page to the browser. This increases server-side rendering performance since the component isn’t rendered on the server.
> perf: defer loading illustrations component to browser

- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/menus/collection-side/collection-side-menu.component.html
- src/app/components/menus/collection-side/collection-side-menu.component.ts
- src/app/components/text-changer/text-changer.component.html
- src/app/components/text-changer/text-changer.component.scss
- src/app/components/text-changer/text-changer.component.ts
- src/app/pages/collection/cover/collection-cover.page.html
- src/app/pages/collection/foreword/collection-foreword.page.html
- src/app/pages/collection/introduction/collection-introduction.page.html
- src/app/pages/collection/text/collection-text.page.html
- src/app/pages/collection/title/collection-title.page.html
- src/app/services/collection-toc.service.ts
This commit fixes a bug introduced by [a25be18](https://github.com/slsfi/digital-edition-frontend-ng/commit/a25be1899f2e35e3cb8dec398907738bc573427b) leading to the document title not being set on collection pages if opting out of server-side rendering of the collection side menu. Previously the document title was set for collection pages by the collection side menu component, but since it’s not necessarily always loaded by SSR, the functionality has been moved to the text-changer component, which is always loaded. Several improvements to the collection side menu and the text-changer have also been made. For instance, the collection TOC is loaded in a service and utilized by both components, eliminating the need to load the same TOC twice, and the previous/next text buttons in the …
> fix: document title not set by SSR

- CHANGELOG.md
- src/app/app.module.ts
- src/app/services/platform.service.ts
Previously the app was set to mobile mode on all touchscreen devices, which was not optimal for e.g. laptops with touchscreens.
> fix: correctly infer app mode on touch devices

- CHANGELOG.md
- package-lock.json
- package.json
xliff was used by an old script that converted legacy i18n json-files to xliff-format, but the script has been removed a long time ago.
> build(deps): remove xliff

- CHANGELOG.md
- src/app/components/pdf-viewer/pdf-viewer.component.html
- src/app/pages/ebook/ebook.page.html
- src/app/pages/ebook/ebook.page.ts
Defer loading of the epub viewer component to the browser, since it’s not SSR-compatible. The epub title is shown as a `<h1>` placeholder in the server response. Also show pdf title as `<h1>` in the pdf viewer component.
> refactor: defer loading epub viewer to browser

- CHANGELOG.md
- package-lock.json
- package.json
- Memory leak related to BehaviorSubject-subscription in the download-texts modal. Also, as a precation, unsubscribe from all route subscriptions on component destruction. ([b32dfe4](https://github.com/slsfi/digital-edition-frontend-ng/commit/b32dfe4e74393ecb64aad4f83d415fa60f2f37bb))
[1.3.1]: https://github.com/slsfi/digital-edition-frontend-ng/compare/1.3.0...1.3.1
> chore: release v1.3.1

- CHANGELOG.md
- src/app/directives/draggable-image.directive.ts
In edge cases, this fixes a potential memory leak on the client side.
> fix: ensure cleanup of event listeners in the draggable-image directive

- CHANGELOG.md
- angular.json
browserTarget has been deprecated.
> refactor: replace browserTarget with buildTarget in extract-i18n options

- CHANGELOG.md
- src/app/components/menus/main-side/main-side-menu.component.ts
If a collection group contains just one collection, the group menu item will not be collapsible/expandable, instead the menu item will link directly into the collection. The menu item title will still be the title of the collection group (defined in translation xliff-files).
> refactor: unwrap lone grouped collections in the main side menu

- CHANGELOG.md
- package-lock.json
- package.json
- Legacy key-value format for `NODE_ENV` in `Dockerfile`. ([385b67e](https://github.com/slsfi/digital-edition-frontend-ng/commit/385b67e3d0303b84dabe41185c5299ca19da4191))
- Docs: refactor code snippets in the development notes and add note about NgModules. ([c3552a9](https://github.com/slsfi/digital-edition-frontend-ng/commit/c3552a9aa05dea9a2c56bc8da9cdc94b00f6589e))
- Deps: update `@angular` to 18.1.1. ([9af16d9](https://github.com/slsfi/digital-edition-frontend-ng/commit/9af16d9e62e3785117e4179e8187a0de52a92182))
- Deps: update `marked` to 13.0.2. ([6471779](https://github.com/slsfi/digital-edition-frontend-ng/commit/647177992e61b752eed1a1d460c7ce0dba5bf9fe))
- Deps: update `zone.js` to 0.14.8 (includes SSR memory leakage fix). …
> chore: release v1.4.3

- CHANGELOG.md
- src/app/components/text-changer/text-changer.component.ts
Match type when comparing collection IDs in text-changer component (i.e. allow `collectionId` to be either string or number in table of content JSON-files).
> fix(text-changer): match type in collectionId comparison

- CHANGELOG.md
- src/app/pages/home/home.page.scss
Home page banner image `min-height` set to `200px` in landscape image mode. This fixes an issue where the banner image height is too small on mobile phones in landscape orientation. You should adjust the `min-height` for the banner image in your project in `custom.scss` if necessary. You can use the selector `page-home div.banner.banner`.
> fix(page-home): pin landscape banner image min-height

- .github/dependabot.yml
- CHANGELOG.md
Dependabot can update minor and patch versions of all dependencies except `@angular` packages, which are updated manually.
> build: configure dependabot version updates

- CHANGELOG.md
- src/app/pages/home/home.page.scss
The landscape banner image height is reduced to 40% on viewport widths less than 1100px.
> refactor(home-page): reduce landscape banner height

- CHANGELOG.md
- src/app/components/menus/main-side/main-side-menu.component.ts
- src/app/components/text-changer/text-changer.component.ts
- src/app/pages/collection/cover/collection-cover.page.html
- src/app/pages/collection/cover/collection-cover.page.ts
- src/app/pages/collection/foreword/collection-foreword.page.html
- src/app/pages/collection/foreword/collection-foreword.page.ts
- src/app/pages/collection/introduction/collection-introduction.page.html
- src/app/pages/collection/introduction/collection-introduction.page.ts
- src/app/pages/collection/text/collection-text.page.html
- src/app/pages/collection/text/collection-text.page.ts
- src/app/pages/collection/title/collection-title.page.html
- src/app/pages/collection/title/collection-title.page.ts
- src/app/services/document-head.service.ts
Prior to this fix the document title was not set correctly when going back to a collection page that had already been visited. This was because in Ionic, the components are not destroyed when leaving views, but saved in a nav stack. The fix uses the Ionic life cycle hooks ionViewWillEnter and ionViewWillLeave on the collection pages to keep track of if the component is active or not, and this information is passed to the text-changer component which sets the document title.
The text-changer component has been refactored to get the information about the current page from the router instead of from input variables.
The document head service has been optimized to avoid unnecessary DOM updates by setting the document title only if it changes.
> fix: correctly set document title on revisiting collection pages in nav stack

- CHANGELOG.md
- prebuild-generate-static-collection-menus.js
Generate static collection menus prebuild script: skip collections that are not included according to the config.
> fix(prebuild-generate-static-collection-menus): skip excluded collections

- CHANGELOG.md
- prebuild-generate-sitemap.js
Generate sitemap prebuild script: skip collections that are not included according to the config.
> fix(prebuild-generate-sitemap): skip excluded collections

- CHANGELOG.md
- src/app/components/menus/collection-side/collection-side-menu.component.html
- src/app/components/menus/collection-side/collection-side-menu.component.ts
- src/app/components/text-changer/text-changer.component.ts
Adds support for custom names for the collection frontmatter pages (cover, title, foreword and introduction). By default, all collections have the same names for the frontmatter pages, set in the translation files in `src/locale/`. The names of these pages can now be set differently for each collection in the JSON table of contents (ToC) files of the collections. The root object in the JSON ToC-files can optionally take the keys `coverPageName`, `titlePageName`, `forewordPageName` and `introductionPageName`. If any of these are set (i.e. have truthy values), those page names are used instead of the default ones. Example of a JSON ToC-file where the introduction page of a particular collection has a non-default name:
```json
{
"text": "About Wittgenstein",
"collectionId": "225",
"type": …
```
> feature: custom frontmatter page names

- CHANGELOG.md
- src/app/components/collection-text-types/facsimiles/facsimiles.component.ts
- src/app/components/collection-text-types/variants/variants.component.ts
- src/app/pages/collection/text/collection-text.page.html
- src/app/pages/collection/text/collection-text.page.ts
When navigating from one collection text to another and you have a facsimile view open, a facsimile from the selected facsimile collection is opened if applicable to the new text. The preservation is performed based on the priority/sortOrder of the facsimiles linked to the text. So if a text has two linked facsimiles, with priorities 1 and 2, each opened in a view, and the user navigates to the next text, the facsimile views are loaded with facsimiles with priorities 1 and 2, if the new text has such facsimiles.
> fix: preserve selected facsimile collection on text change

- CHANGELOG.md
- src/app/components/collection-text-types/variants/variants.component.html
- src/app/dialogs/popovers/view-options/view-options.popover.html
- src/app/dialogs/popovers/view-options/view-options.popover.scss
- src/app/dialogs/popovers/view-options/view-options.popover.ts
- src/app/pages/collection/text/collection-text.page.ts
- src/app/services/view-options.service.ts
- src/assets/config/config.ts
- src/locale/messages.en.xlf
- src/locale/messages.fi.xlf
- src/locale/messages.sv.xlf
- src/locale/messages.xlf
- src/theme/TEI/_tei-variants.scss
Added config option `config.page.text.variantViewOptions` to allow the user to control the type of variation that is displayed in variant texts. It has two properties: `showVariationTypeOption`, which is a boolean used to control if the view option should be shown or not (defaults to `false`), and `defaultVariationType`, which is a string used to set the variation type that is shown by default. Possible values include `all` (default) for displaying all variation types, `sub` for displaying only substantial/significant variation, and `none` for hiding all variation highlighting. Example:
```typescript
export const config: Config = {
/*...*/
page: {
/*...*/
text: {
/*...*/
variantViewOptions: {
showVariationTypeOption: true,
defaultVariationType: "sub"
},
/*...*/
},
/*...*/
},
/*...*/
}
```
> feature: variation type view option for variants

- CHANGELOG.md
- src/app/components/menus/main-side/main-side-menu.component.html
- src/app/components/menus/main-side/main-side-menu.component.scss
- src/app/components/menus/main-side/main-side-menu.component.ts
- src/assets/config/config.ts
The config option `component.mainSideMenu.items.home` is removed. The home button is always shown in the main side menu.
> feature: add always present home button to main side menu

- CHANGELOG.md
- src/app/components/collection-text-types/comments/comments.component.ts
- src/app/components/collection-text-types/facsimiles/facsimiles.component.ts
- src/app/components/collection-text-types/illustrations/illustrations.component.ts
- src/app/components/collection-text-types/legend/legend.component.ts
- src/app/components/collection-text-types/manuscripts/manuscripts.component.ts
- src/app/components/collection-text-types/metadata/metadata.component.ts
- src/app/components/collection-text-types/reading-text/reading-text.component.ts
- src/app/components/collection-text-types/variants/variants.component.ts
- src/app/dialogs/modals/download-texts/download-texts.modal.ts
- src/app/models/collection.model.ts
- src/app/pages/collection/introduction/collection-introduction.page.ts
- src/app/pages/collection/text/collection-text.page.html
- src/app/pages/collection/text/collection-text.page.ts
- src/app/services/collection-content.service.ts
- src/app/services/comment.service.ts
- src/app/services/html-parser.service.ts
- src/app/services/tooltip.service.ts
Instead of passing a string consisting of the current collection, publication and optional chapter id to dependent components, pass an object (TextKey) holding the properties.
> refactor: collection text id handling
